/** @file FileIO.cpp
 * @brief file defining methods to read points from a file
 * see FileIO.h for methods declaration
 * @author Julie Digne julie.digne@liris.cnrs.fr
 * @date 2012/10/22
 * @copyright This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "FileIO.h"
#include <iostream>
#include <fstream>
#include <istream>
#include <ostream>
#include <sstream>
#include <limits>

using namespace std;

FileIO::FileIO()
{
}

FileIO::~FileIO()
{
}

std::string FileIO::baseOutputFilename;

#ifdef _DEBUG
bool FileIO::debugSavePoints(const char *filename, OctreeVertices &octree)
{
    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
        return false;

    OctreeNodeV *node = octree.getRoot();
    saveContent(node, out);

    out.close();

    return true;
}
#endif

bool FileIO::debugSavePLY(const char *output_filename, Mesher &mesher)
{
    std::string filename = baseOutputFilename + output_filename;

    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
    { // file couldn't be opened
        cerr << "Error: file could not be opened" << endl;
        return false;
    }

    out << "ply" << endl;
    out << "format ascii 1.0" << endl;
    out << "comment Mesh generated by the Ball Pivoting Algorithm" << endl;
    out << "element vertex " << mesher.nVertices() << endl;
    out << "property float x" << endl;
    out << "property float y" << endl;
    out << "property float z" << endl;
    out << "property float nx" << endl;
    out << "property float ny" << endl;
    out << "property float nz" << endl;
    out << "element face " << mesher.nFacets() << endl;
    out << "property list uchar int vertex_indices" << endl;
    out << "end_header" << endl;

    // Remark that edge is not needed for create the mesh.

    for (Vertex_star_list::const_iterator vi = mesher.vertices_begin();
         vi != mesher.vertices_end(); ++vi)
    {
        Vertex *v = *vi;
        out << *v << endl;
    }

    for (Facet_star_list::const_iterator fi = mesher.facets_begin();
         fi != mesher.facets_end(); ++fi)
    {
        out << 3 << "\t";
        const Facet *f = *fi;

        Vertex *v0 = f->vertex(0);
        Vertex *v1 = f->vertex(1);
        Vertex *v2 = f->vertex(2);

        double nx = v0->nx() + v1->nx() + v2->nx();
        double ny = v0->ny() + v1->ny() + v2->ny();
        double nz = v0->nz() + v1->nz() + v2->nz();

        double tx = v1->x() - v0->x();
        double ty = v1->y() - v0->y();
        double tz = v1->z() - v0->z();

        double sx = v2->x() - v0->x();
        double sy = v2->y() - v0->y();
        double sz = v2->z() - v0->z();

        double cprodx, cprody, cprodz;
        cross_product(tx, ty, tz, sx, sy, sz, cprodx, cprody, cprodz);

        if (nx * cprodx + ny * cprody + nz * cprodz > 0)
        {
            out << v0->index() << "\t";
            out << v1->index() << "\t";
            out << v2->index() << endl;
        }
        else
        {
            out << v0->index() << "\t";
            out << v2->index() << "\t";
            out << v1->index() << endl;
        }
    }
    return true;
}

void FileIO::saveContent(OctreeNodeV *node, ofstream &f)
{
    if (node->getDepth() != 0)
    {
        for (int i = 0; i < 8; i++)
            if (node->getChild(i) != nullptr)
                saveContent(node->getChild(i), f);
    }
    else if (node->getNpts() != 0)
    {
        // Vertex_list::const_iterator iter;
        // for(iter = node->points_begin(); iter != node->points_end();
        //     ++iter)
        //{
        //     f << *iter <<std::endl;
        // }
        Vertex_UnOrdSet::const_iterator iter;
        for (iter = node->points_begin(); iter != node->points_end();
             ++iter)
        {
            Vertex *v = *iter;
            f << *v << std::endl;
        }
    }
}

// add by mauhing
std::vector<string> FileIO::readIntoFileBatch(const char *filenames)
{
    if (!filenames)
    {
        throw std::invalid_argument("Null filename provided");
    }

    // get the filename first.
    std::string filename = filenames;
    std::vector<string> batch_data;

    std::ifstream whole_data(filename);
    if (!whole_data.is_open())
    {
        throw std::runtime_error("Could not open file: " + filename);
    }

    // read the file line by line.
    std::string line;
    std::string temp_data;
    while (std::getline(whole_data, line))
    {
        // if the line did not start with ===, we add it into temp_data
        if (line.substr(0, 3) != "===")
        {
            temp_data += line + "\n";
        }
        if (line.substr(0, 3) == "===")
        {
            batch_data.push_back(temp_data);
            temp_data = "";
        }
        // if next line is empty, we add the last temp_data into batch_data
        if (whole_data.peek() == '\n')
        {
            batch_data.push_back(temp_data);
            temp_data = "";
        }
        if (whole_data.eof())
        {
            batch_data.push_back(temp_data);
        }
    }

    whole_data.close();
    return batch_data;
}

std::tuple<Point, double, unsigned int> FileIO::originAndDepth(const string &batch_data, double min_radius)
{
    double x, y, z, nx, ny, nz;
    istringstream batch_data_in(batch_data);
    batch_data_in >> x >> y >> z >> nx >> ny >> nz;

    list<Vertex> input_vertices;
    input_vertices.push_back(Vertex(x, y, z, nx, ny, nz));

    // >>> initialize bounding box
    double xmin, ymin, zmin, xmax, ymax, zmax;
    xmin = xmax = x;
    ymin = ymax = y;
    zmin = zmax = z;
    // <<<

    // >>> read the rest of the file and find the bounding box
    while (batch_data_in >> x >> y >> z >> nx >> ny >> nz)
    {
        input_vertices.push_back(Vertex(x, y, z, nx, ny, nz));

        xmin = x < xmin ? x : xmin;
        xmax = x > xmax ? x : xmax;
        ymin = y < ymin ? y : ymin;
        ymax = y > ymax ? y : ymax;
        zmin = z < zmin ? z : zmin;
        zmax = z > zmax ? z : zmax;
    }
    // <<<
    std::cout << input_vertices.size() << " points read" << std::endl;

    double lx = xmax - xmin;
    double ly = ymax - ymin;
    double lz = zmax - zmin;

    // Get size of one of the largest dimension
    double size = lx > ly ? lx : ly;
    size = size > lz ? size : lz;

    size = 1.1 * size;
    double margin;

    unsigned int depth = 0;
    if (min_radius > 0)
    {
        depth = (unsigned int)ceil(log2(size / (min_radius)));
        double adapted_size = pow2(depth) * min_radius;
        margin = 0.5 * (adapted_size - size);
        size = adapted_size;
    }
    else
    {
        std::cerr << "Warning: min_radius has to bigger than 0" << std::endl;
        std::exit(EXIT_FAILURE);
    }

    // The orgin of the octree is the lower left corner (2D) of the bounding box
    double ox = xmin - margin;
    double oy = ymin - margin;
    double oz = zmin - margin;
    Point origin(ox, oy, oz);

    return std::tuple<Point, double, unsigned int>(origin, size, depth);
}

bool FileIO::saveMeshDebug(const char *filename, Mesher &mesher)
{
    return saveMeshDebug(filename, mesher.getFacets());
}

bool FileIO::saveMeshDebug(const char *output_filename, const std::list<Facet *> &facets)
{
    std::string filename = baseOutputFilename + output_filename;

    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
    { // file couldn't be opened
        cerr << "Error: file could not be opened" << endl;
        return false;
    }

    out << "The first section will be idx, x, y, z, nx, ny, nz" << endl;
    out << "The second section will be 3, idx0, idx1, idx2" << endl;

    std::unordered_map<int, Vertex *> vertices;
    for (std::list<Facet *>::const_iterator fi = facets.begin();
         fi != facets.end(); ++fi)
    {
        for (int i = 0; i < 3; ++i)
        {
            const Facet *f = *fi;
            Vertex *v = f->vertex(i);
            vertices[v->index()] = v;
        }
    }
    for (auto &pair : vertices)
    {
        Vertex *v = pair.second;
        out << v->index() << "\t" << v->x() << "\t" << v->y() << "\t" << v->z() << "\t" << v->nx() << "\t" << v->ny() << "\t" << v->nz() << endl;
    }

    // add a blank line
    out << endl;

    for (std::list<Facet *>::const_iterator fi = facets.begin();
         fi != facets.end(); ++fi)
    {
        out << 3 << "\t";
        const Facet *f = *fi;

        Vertex *v0 = f->vertex(0);
        Vertex *v1 = f->vertex(1);
        Vertex *v2 = f->vertex(2);

        double nx = v0->nx() + v1->nx() + v2->nx();
        double ny = v0->ny() + v1->ny() + v2->ny();
        double nz = v0->nz() + v1->nz() + v2->nz();

        double tx = v1->x() - v0->x();
        double ty = v1->y() - v0->y();
        double tz = v1->z() - v0->z();

        double sx = v2->x() - v0->x();
        double sy = v2->y() - v0->y();
        double sz = v2->z() - v0->z();

        double cprodx, cprody, cprodz;
        cross_product(tx, ty, tz, sx, sy, sz, cprodx, cprody, cprodz);

        // << Ensure orientation
        if (nx * cprodx + ny * cprody + nz * cprodz > 0)
        {
            out << v0->index() << "\t";
            out << v1->index() << "\t";
            out << v2->index() << endl;
        }
        else
        {
            out << v0->index() << "\t";
            out << v2->index() << "\t";
            out << v1->index() << endl;
        }
        // >>
    }
    out.close(); // close the file
    return true;
}

std::list<Vertex> FileIO::readFromBatchToList(const string &batch_data)
{
    // batch data has format:
    // x y z nx ny nz
    // x y z nx ny nz
    // ...

    double x, y, z, nx, ny, nz;
    istringstream batch_data_in(batch_data);
    batch_data_in >> x >> y >> z >> nx >> ny >> nz;

    list<Vertex> input_vertices;
    input_vertices.push_back(Vertex(x, y, z, nx, ny, nz));

    // >>> read the rest of the file and find the bounding box
    while (batch_data_in >> x >> y >> z >> nx >> ny >> nz)
    {
        input_vertices.push_back(Vertex(x, y, z, nx, ny, nz));
    }
    // <<<
    std::cout << input_vertices.size() << " points read" << std::endl;

    return input_vertices;
}

#ifdef _DEBUG
bool FileIO::debugSaveLineset(const char *output_filename, const Edge_star_list &border_edges)
{
    std::string filename = baseOutputFilename + output_filename;

    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
    { // file couldn't be opened
        cerr << "Error: file could not be opened" << endl;
        return false;
    }

    for (auto &edge : border_edges)
    {
        Vertex *v0 = edge->getSource();
        Vertex *v1 = edge->getTarget();
        out << v0->x() << "\t" << v0->y() << "\t" << v0->z() << "\t" << v1->x() << "\t" << v1->y() << "\t" << v1->z() << endl;
    }
    out.close(); // close the file
    return true;
}
#endif

bool FileIO::debugSaveBallCenters(const char *output_filename, const Point_UnOrdSet &ball_centers, const double &radius)
{
    std::string filename = baseOutputFilename + output_filename;

    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
    { // file couldn't be opened
        cerr << "Error: file could not be opened" << endl;
        return false;
    }

    // First line is explaination
    out << "Line 2: radius. Rest of the lines are x, y, z" << endl;

    // Save the radius
    out << radius << endl;

    // Save the ball centers
    for (auto &center : ball_centers)
    {
        out << center->x() << "\t" << center->y() << "\t" << center->z() << endl;
    }

    out.close();
    return true;
}

bool FileIO::debugSavePoints(const char *output_filename, const Point_UnOrdSet &points)
{
    std::string filename = baseOutputFilename + output_filename;

    ofstream out;
    out.open(filename);
    out.precision(numeric_limits<double>::digits10 + 1);

    if (!out)
    { // file couldn't be opened
        cerr << "Error: file could not be opened" << endl;
        return false;
    }

    // Save the points
    for (auto &point : points)
    {
        out << point->x() << "\t" << point->y() << "\t" << point->z() << endl;
    }

    out.close();
    return true;
}

void FileIO::setBaseOutputFilename(const std::string &filename)
{
    baseOutputFilename = filename;
}